name: Dependent scanning
on:
  push:
    branches:
      - main # run the action on your projects default branch

jobs:
  build:
    runs-on: windows-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
     - name: 'Checkout Repository'
       uses: actions/checkout@v3
     - name: Gradle Dependency Submission
       uses: mikepenz/gradle-dependency-submission@v0.8.3
       with:
          use-gradlew: true
          gradle-project-path: "./"
          gradle-build-module: |-
           :
           :klogger
           :compiler
          gradle-build-configuration: |-
           compileClasspath
   
